'use client';
import Link from 'next/link';
import {useQuery} from '@tanstack/react-query';
import {pilotApi, number, day} from '@/features/monitoring/api';
import type {ModelReport, AlertMetrics} from '@/features/monitoring/types';

const percent = (v: number | null | undefined) => (v === null || v === undefined) ? '—' : `${v.toLocaleString('ru-RU', {maximumFractionDigits:2})}%`;
const decimal = (v: number | undefined) => (v === null || v === undefined) ? '—' : v.toLocaleString('ru-RU',{maximumFractionDigits:4});
function RiskMetrics({rows}:{rows:{name:string;metrics:AlertMetrics}[]}){
 return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{['Вариант / период','Precision','Recall','F2','TP / FP / FN / TN','Тревог'].map(s=><th key={s} className="p-2">{s}</th>)}</tr></thead><tbody>{rows.map(({name,metrics:m})=><tr key={name} className="border-b"><td className="p-2 font-medium">{name}</td><td className="p-2">{percent(m.true_positive+m.false_positive ? m.precision_percent : null)}</td><td className="p-2">{percent(m.true_positive+m.false_negative ? m.recall_percent : null)}</td><td className="p-2">{decimal(m.f2)}</td><td className="whitespace-nowrap p-2">{m.true_positive} / {m.false_positive} / {m.false_negative} / {m.true_negative}</td><td className="p-2">{m.true_positive+m.false_positive}</td></tr>)}</tbody></table></div>;
}
export default function ModelPage(){
 const query=useQuery({queryKey:['pilot-model'],queryFn:()=>pilotApi<ModelReport>('model'),retry:1,refetchInterval:10000}); const r=query.data;
 if(query.error)return <div role="alert"><p>{query.error.message}</p><button onClick={()=>void query.refetch()} className="mt-3 rounded-lg border px-4 py-2">Повторить</button></div>;
 if(!r)return <p>Загрузка отчёта об обучении…</p>;
 const comparison=[...(r.previous?[{name:'Предыдущая модель',metrics:r.previous.alert_test}]:[]),{name:'Текущая модель',metrics:r.alert_test}];
 return <div className="mx-auto max-w-6xl space-y-6">
  <Link className="text-sm text-teal-700" href="/monitor">← Предупреждения</Link>
  <header className="rounded-3xl bg-[#10334a] p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-teal-200">Обучение на реальных данных</p><h1 className="mt-3 text-3xl font-semibold">Качество модели — с доказательствами</h1><p className="mt-3 text-sm text-slate-200">Прогноз количества и обнаружение риска проверяются отдельно.</p><p className="mt-3 break-all text-xs text-teal-200">Версия: {r.model_id} · обучено {new Date(r.trained_at).toLocaleString('ru-RU')}</p></header>
  <section className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-950"><h2 className="text-lg font-semibold">Повторная оценка, не новый независимый тест</h2><p className="mt-2 text-sm">Период {day(r.test_start)} — {day(r.test_end)} уже исследовался в предыдущей итерации. Параметры этой серии выбраны на более ранней валидации. Для независимого подтверждения нужен новый период данных.</p><p className="mt-2 text-sm">Больше найденных событий может означать больше ложных тревог. Пилот пока не готов к самостоятельному контролю перегрузки.</p></section>
  <section className="surface-card rounded-2xl p-6"><h2 className="text-lg font-semibold">Предупреждения: до и после</h2><p className="my-3 text-sm text-muted-foreground">Те же {r.hospitals} организаций, две недельные проверки. Событие: поток ≥120% обычной недели за предыдущие 28 дней, прирост ≥10, обычный поток ≥20.</p><RiskMetrics rows={comparison}/><p className="mt-3 text-sm">Precision — доля подтвердившихся тревог. Recall — доля найденных эпизодов роста. F2 придаёт полноте больший вес. TP — найденные события, FP — ложные тревоги, FN — пропуски, TN — верно не поднятая тревога.</p><p className="mt-3 text-sm font-semibold">Текущая модель: {r.alert_test.true_positive} найдено, {r.alert_test.false_positive} ложных тревог, {r.alert_test.false_negative} пропущено. {r.alert_test.alert_rate_percent!==undefined && <>Доля тревог среди проверок: {percent(r.alert_test.alert_rate_percent)}.</>}</p></section>
  <section className="surface-card rounded-2xl p-6"><h2 className="text-lg font-semibold">Численный прогноз: ошибка на том же периоде</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Метод</th><th>MAE, направлений/день</th><th>WAPE</th></tr></thead><tbody>{[...(r.previous?[{name:'Предыдущая модель',m:r.previous.test.ml}]:[]),{name:'Текущая модель',m:r.test.ml},{name:'Повтор прошлой недели',m:r.test.weekly_naive},{name:'Среднее за 7 дней',m:r.test.mean7}].map(({name,m})=><tr className="border-b" key={name}><td className="p-2">{name}</td><td>{decimal(m.mae)}</td><td>{percent(m.wape)}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm">MAE — средняя абсолютная ошибка по организации и дню. WAPE — сумма абсолютных ошибок относительно фактического потока. Меньше — лучше. Это не точность классификатора риска.</p></section>
  <section className="surface-card rounded-2xl p-6"><h2 className="text-lg font-semibold">Как выбирали модель</h2><ol className="mt-3 space-y-2 text-sm"><li>1. Обучение на данных {day(r.period_start)} — {day(r.train_end)}. Целые целевые недели классификатора остаются внутри обучения.</li><li>2. Выбор алгоритма и порога: {day(r.validation_start)} — {day(r.validation_end)}. Максимум F2 при precision ≥40% и доле тревог ≤25% на валидации.</li><li>3. После фиксации выбора — повторная оценка {day(r.test_start)} — {day(r.test_end)}. Порог по этому результату не меняется.</li></ol>{r.selection && <p className="mt-3 text-sm">Выбран детектор {r.selection.risk_model}, численный прогноз {r.selection.regressor}. {Object.keys(r.selection.segment_thresholds).length ? 'Пороги различаются по объёму организации, определённому только по обучающему периоду.' : `Порог ${decimal(r.selection.threshold)}.`} Score — оценка модели, не калиброванная вероятность.</p>}{r.alert_validation && <div className="mt-4"><RiskMetrics rows={[{name:'Валидация выбранного варианта',metrics:r.alert_validation}]}/></div>}</section>
  {r.experiments && <details className="surface-card rounded-2xl p-6"><summary className="cursor-pointer font-semibold">Все эксперименты и результаты валидации</summary><div className="mt-4"><RiskMetrics rows={r.experiments.map(e=>({name:e.name,metrics:e.validation}))}/></div><p className="mt-3 text-xs">Варианты, не прошедшие ограничения precision и числа тревог, не выбирались. Численный прогноз выбирался отдельно по минимальному MAE.</p>{r.numeric_experiments?.map(e=><p className="mt-2 text-sm" key={e.name}>{e.name}: MAE {decimal(e.validation.ml.mae)}, WAPE {percent(e.validation.ml.wape)}</p>)}</details>}
  {r.alert_folds && <section className="surface-card rounded-2xl p-6"><h2 className="mb-3 text-lg font-semibold">Устойчивость по неделям и группам</h2><RiskMetrics rows={r.alert_folds.map(f=>({name:`Неделя после ${day(f.as_of)}`,metrics:f.metrics}))}/>{r.segment_metrics && <div className="mt-4"><RiskMetrics rows={Object.entries(r.segment_metrics).map(([name,metrics])=>({name:`Объём: ${name}`,metrics}))}/></div>}<p className="mt-3 text-xs">Группы по среднему дневному потоку в обучении: small &lt;10; medium от 10 до 50; large ≥50. Одна организация даёт две проверки.</p>{r.earlier_check && <div className="mt-4"><p className="mb-2 text-sm">Дополнительная ранняя проверка: обучение до {day(r.earlier_check.train_end)}, {r.earlier_check.hospitals} организаций. Диагностика выбранной архитектуры с общим порогом, не независимое доказательство выбора.</p><RiskMetrics rows={[{name:'Ранний период',metrics:r.earlier_check.metrics}]}/></div>}</section>}
  <section className="surface-card rounded-2xl p-6"><h2 className="text-lg font-semibold">Данные и ограничения</h2><p className="mt-3 text-sm">{number(r.source.rows)} записей, {r.hospitals} организаций. {number(r.training_examples)} примеров численного прогноза; {number(r.risk_training_examples ?? 0)} недельных примеров риска. {r.excluded_hospitals} организаций не прошли критерии наличия истории.</p>{r.source_audit && <p className="mt-2 text-sm">Аудит: {r.source_audit.dates} дат; точных повторов строк {r.source_audit.exact_duplicate_rows}; повторяющихся кодов случаев {r.source_audit.repeated_case_codes}. Ни один сложный период не исключён.</p>}<ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{r.limitations.map(l=><li key={l}>{l}</li>)}</ul><a className="mt-4 inline-block text-sm text-teal-700 underline" href={r.source.source_url} target="_blank" rel="noreferrer">Источник: Ashyq Data</a></section>
  <details className="surface-card rounded-2xl p-6 text-sm"><summary className="cursor-pointer font-semibold">Артефакты и происхождение результатов</summary><div className="mt-4 space-y-2 break-all"><p>Алгоритм: {r.model}</p><p>Версия: {r.model_id}</p><p>SHA-256 модели: {r.artifact_sha256}</p><p>SHA-256 исходных файлов: {r.dataset_sha256}</p><p>Предыдущая версия: {r.previous?.model_id ?? '—'}</p><p>Признаки прогноза: {r.features.join(', ')}</p></div></details>
 </div>;
}
