"""Доменный фундамент (PHASE 2).

Справочники, пользователи и области данных, сигналы с объяснением,
инциденты, действия, метаданные прогнозов и сценариев, импорты
и журнал аудита.

Аналитические временные ряды здесь не создаются: они относятся
к ClickHouse и появляются после Data Audit (ADR-0007, ADR-0002).

Revision ID: 0002_domain_foundation
Revises: 0001_system_operations
Create Date: PHASE 2

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_domain_foundation"
down_revision: str | None = "0001_system_operations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("code", name=op.f("uq_regions_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_actor_user_id_created_at",
        "audit_events",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_created_at", "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_entity_type_entity_id",
        "audit_events",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_request_id", "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "data_imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_type", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_hash", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_data_imports_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_imports")),
        sa.UniqueConstraint(
            "dataset_type", "file_hash", name="uq_data_imports_dataset_type_file_hash"
        ),
    )
    op.create_index(
        "ix_data_imports_file_hash", "data_imports", ["file_hash"], unique=False
    )
    op.create_index(
        "ix_data_imports_status_created_at",
        "data_imports",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "hospitals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_hospitals_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospitals")),
        sa.UniqueConstraint("code", name=op.f("uq_hospitals_code")),
    )
    op.create_index("ix_hospitals_region_id", "hospitals", ["region_id"], unique=False)
    op.create_index(
        "ix_hospitals_region_id_is_active",
        "hospitals",
        ["region_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("target", sa.String(length=64), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("predicted_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("lower_bound", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("upper_bound", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("metric_name", sa.String(length=32), nullable=True),
        sa.Column("metric_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("baseline_metric_name", sa.String(length=32), nullable=True),
        sa.Column(
            "baseline_metric_value", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column("input_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("invalidity_reason", sa.Text(), nullable=True),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_forecasts_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
    )
    op.create_index(
        "ix_forecasts_hospital_id_generated_at",
        "forecasts",
        ["hospital_id", "generated_at"],
        unique=False,
    )
    op.create_index(
        "ix_forecasts_hospital_id_target_status",
        "forecasts",
        ["hospital_id", "target", "status"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_incidents_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index("ix_incidents_created_at", "incidents", ["created_at"], unique=False)
    op.create_index(
        "ix_incidents_hospital_id_status",
        "incidents",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_table(
        "user_data_scopes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("hospital_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope_type = 'GLOBAL' AND region_id IS NULL AND hospital_id IS NULL) OR (scope_type = 'REGION' AND region_id IS NOT NULL AND hospital_id IS NULL) OR (scope_type = 'HOSPITAL' AND hospital_id IS NOT NULL AND region_id IS NULL)",
            name=op.f("ck_user_data_scopes_ck_user_data_scopes_target_matches_type"),
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_user_data_scopes_hospital_id_hospitals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_user_data_scopes_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_data_scopes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_data_scopes")),
        sa.UniqueConstraint(
            "user_id",
            "scope_type",
            "region_id",
            "hospital_id",
            name="uq_user_data_scopes_user_id_scope_type_region_id_hospital_id",
        ),
    )
    op.create_index(
        "ix_user_data_scopes_user_id", "user_data_scopes", ["user_id"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_id", sa.UUID(), nullable=True),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("closed_reason", sa.Text(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_signals_ck_signals_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_signals_assigned_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["forecasts.id"],
            name=op.f("fk_signals_forecast_id_forecasts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_signals_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_signals_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(
        "ix_signals_assigned_user_id_status",
        "signals",
        ["assigned_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_signals_hospital_id_detected_at",
        "signals",
        ["hospital_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_signals_hospital_id_status",
        "signals",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index("ix_signals_incident_id", "signals", ["incident_id"], unique=False)
    op.create_index(
        "ix_signals_status_severity_detected_at",
        "signals",
        ["status", "severity", "detected_at"],
        unique=False,
    )
    op.create_index("ix_signals_type", "signals", ["type"], unique=False)
    op.create_table(
        "actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "signal_id IS NOT NULL OR incident_id IS NOT NULL",
            name=op.f("ck_actions_ck_actions_target_present"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_actions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_actions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_actions_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
    )
    op.create_index(
        "ix_actions_incident_id_created_at",
        "actions",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_actions_signal_id_created_at",
        "actions",
        ["signal_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=True),
        sa.Column("scenario_type", sa.String(length=32), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_scenarios_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_scenarios_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_scenarios_signal_id_signals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
    )
    op.create_index(
        "ix_scenarios_created_by_created_at",
        "scenarios",
        ["created_by", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_scenarios_hospital_id_created_at",
        "scenarios",
        ["hospital_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "signal_explanations",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("caveats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generator", sa.String(length=32), nullable=False),
        sa.Column("generator_version", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("input_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_signal_explanations_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("signal_id", name=op.f("pk_signal_explanations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_explanations")
    op.drop_index("ix_scenarios_hospital_id_created_at", table_name="scenarios")
    op.drop_index("ix_scenarios_created_by_created_at", table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index("ix_actions_signal_id_created_at", table_name="actions")
    op.drop_index("ix_actions_incident_id_created_at", table_name="actions")
    op.drop_table("actions")
    op.drop_index("ix_signals_type", table_name="signals")
    op.drop_index("ix_signals_status_severity_detected_at", table_name="signals")
    op.drop_index("ix_signals_incident_id", table_name="signals")
    op.drop_index("ix_signals_hospital_id_status", table_name="signals")
    op.drop_index("ix_signals_hospital_id_detected_at", table_name="signals")
    op.drop_index("ix_signals_assigned_user_id_status", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_user_data_scopes_user_id", table_name="user_data_scopes")
    op.drop_table("user_data_scopes")
    op.drop_index("ix_incidents_hospital_id_status", table_name="incidents")
    op.drop_index("ix_incidents_created_at", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_forecasts_hospital_id_target_status", table_name="forecasts")
    op.drop_index("ix_forecasts_hospital_id_generated_at", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index("ix_hospitals_region_id_is_active", table_name="hospitals")
    op.drop_index("ix_hospitals_region_id", table_name="hospitals")
    op.drop_table("hospitals")
    op.drop_index("ix_data_imports_status_created_at", table_name="data_imports")
    op.drop_index("ix_data_imports_file_hash", table_name="data_imports")
    op.drop_table("data_imports")
    op.drop_index("ix_audit_events_request_id", table_name="audit_events")
    op.drop_index("ix_audit_events_entity_type_entity_id", table_name="audit_events")
    op.drop_index("ix_audit_events_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_user_id_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("regions")
    # ### end Alembic commands ###
