'use client';
import Link from 'next/link';
import {useQuery} from '@tanstack/react-query';
import {pilotApi, number, day} from '@/features/monitoring/api';
import {ErrorState} from '@/features/analytics/components/states';
import type {ModelReport} from '@/features/monitoring/types';
export default function ModelPage(){
 const query=useQuery({queryKey:['pilot-model'],queryFn:()=>pilotApi<ModelReport>('model'),retry:1}); const r=query.data;
 if(query.error)return <ErrorState label="Отчёт о модели временно недоступен. Повторите позже."/>;
 if(!r)return <p>Загрузка отчёта об обучении…</p>;
 return <div className="mx-auto max-w-4xl space-y-6"><Link className="text-sm text-teal-700" href="/monitor">← Предупреждения</Link><div><h1 className="text-3xl font-semibold">Модель действительно обучалась</h1><p className="mt-2 text-muted-foreground">Здесь результаты выполненного обучения на тестовом наборе данных.</p></div>
  <section className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">На чём училась</h2><p className="mt-3">{number(r.source.rows)} записей о направлениях · {r.hospitals} организаций · {number(r.training_examples)} обучающих примеров.</p><p className="mt-2 text-sm">Используются только дата регистрации и принимающая организация. Модель ищет связь между прошлым потоком, днём недели и будущим числом направлений.</p><p className="mt-2 text-sm">{r.excluded_hospitals} организаций исключено: недостаточно истории на момент обучения.</p><a className="mt-3 inline-block text-sm text-teal-700 underline" href={r.source.source_url} target="_blank" rel="noreferrer">Открытый источник: Ashyq Data</a></section>
  <section className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">Как проверяли без подсказки из будущего</h2><ol className="mt-4 space-y-3 text-sm"><li><strong>1. Обучение:</strong> {day(r.period_start)} — {day(r.train_end)}. На этих данных менялись параметры модели.</li><li><strong>2. Проверка и выбор простого сравнения:</strong> {day(r.validation_start)} — {day(r.validation_end)}.</li><li><strong>3. Независимый тест:</strong> {day(r.test_start)} — {day(r.test_end)}. Модель заморожена; результаты этих дней не использовались для обучения.</li></ol><p className="mt-3 text-xs text-muted-foreground">Каждый прогноз строится на 7 дней. Во второй тестовой неделе факты первой уже доступны как история, но модель на них не переобучается.</p></section>
  <section className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">Результат на последних двух неделях</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Метод</th><th>Ошибка, направлений/день</th><th>WAPE</th></tr></thead><tbody>{([['ml','Обученная модель'],['weekly_naive','Повтор прошлой недели'],['mean7','Среднее за 7 дней']] as const).map(([key,label])=><tr className="border-b" key={key}><td className="py-3">{label}</td><td>{number(r.test[key].mae)}</td><td>{r.test[key].wape===null?'—':`${number(r.test[key].wape!)}%`}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm">MAE — средняя абсолютная ошибка по больнице и дню. WAPE — сумма ошибок, делённая на фактический поток. Чем меньше, тем лучше.</p><p className="mt-3 text-sm font-medium">{r.ml_better_on_test?'Модель превзошла выбранный простой прогноз на этом тесте.':'На этом тесте модель не превзошла выбранный простой прогноз.'} Это ещё не подтверждение готовности к эксплуатации.</p><p className="mt-2 text-sm">На отдельной неделе относительная ошибка может превышать 100% при резком падении потока.</p></section>
  <section className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-950"><h2 className="text-lg font-semibold">Проверка самих предупреждений</h2><p className="mt-3 text-sm">Из {r.alert_test.true_positive+r.alert_test.false_positive} предупреждений на двух тестовых неделях рост подтвердился в {r.alert_test.true_positive}. Ложных предупреждений: {r.alert_test.false_positive}; пропущенных эпизодов роста: {r.alert_test.false_negative}.</p><p className="mt-2 text-sm">Точность предупреждений: {r.alert_test.precision_percent ?? '—'}%. Найдено эпизодов роста: {r.alert_test.recall_percent ?? '—'}%.</p><p className="mt-3 text-sm font-semibold">Пока это исследовательский пилот: полнота обнаружения низкая. Использовать его как единственный канал контроля нельзя.</p><p className="mt-2 text-xs">Проверяется рост числа направлений по тому же порогу, а не фактическая перегрузка больницы.</p></section>
  <section className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">Что пока не доказано</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{r.limitations.map(l=><li key={l}>{l}</li>)}</ul></section>
  <details className="rounded-xl border p-6 text-sm"><summary className="cursor-pointer font-semibold">Проверяемые артефакты обучения</summary><div className="mt-4 space-y-2 break-all"><p>Алгоритм: {r.model}</p><p>Модель: {r.model_id}</p><p>Обучено: {new Date(r.trained_at).toLocaleString('ru-RU')}</p><p>SHA-256 сохранённой модели: {r.artifact_sha256}</p><p>SHA-256 набора файлов: {r.dataset_sha256}</p><p>Признаки: {r.features.join(', ')}</p></div></details>
 </div>;
}
