export type Metric = {mae: number; wape: number | null; points: number};
export type Alert = {
  id: string; hospital: string; as_of: string; severity: 'WARNING' | 'HIGH' | 'CRITICAL';
  title: string; description: string; why_dangerous: string; predicted_total: number;
  reference_total: number; extra_referrals: number; growth_percent: number;
  model_id: string; status: 'NEW' | 'IN_PROGRESS' | 'CLOSED'; current_as_of?: string;
  quality: {validation_ml: Metric; validation_baseline: Metric; baseline: string; weekly_error_max: number; status: string};
  forecast: {date: string; value: number}[];
  actions: {owner: string; when: string; text: string; check: string}[];
  action_basis: string; effect: string; trigger: string;
};
export type Monitor = {as_of: string; new_records: number; hospitals_checked: number; alerts: Alert[];
  running: boolean; index: number; total_steps: number; finished: boolean; updated_at: string | null;
  interval_seconds: number; model_id: string; prediction_mode: string};
export type ModelReport = {model_id: string; model: string; trained_at: string; features: string[];
  train_end: string; period_start: string; period_end: string; validation_start: string; validation_end: string;
  test_start: string; test_end: string; training_examples: number; hospitals: number; excluded_hospitals: number;
  source: {rows: number; accepted: number; invalid: number; source_url: string; files: {name: string; sha256: string; rows: number}[]};
  validation: Record<'ml'|'weekly_naive'|'mean7', Metric>;
  test: Record<'ml'|'weekly_naive'|'mean7', Metric> & {folds: {start: string; end: string; ml: Metric; weekly_naive: Metric}[]};
  baseline: 'weekly_naive' | 'mean7'; ml_better_on_test: boolean; limitations: string[];
  alert_test: {true_positive:number; false_positive:number; false_negative:number; precision_percent:number|null; recall_percent:number|null};
  artifact_sha256: string; dataset_sha256: string;
};
